apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysflow-agent
  labels:
    {{- include "sysflowagent.labels" . | nindent 4 }}
imagePullSecrets:
- name: sa-{{ .Release.Namespace }}
{{- with .Values.imagePullSecrets }}
{{- toYaml . | nindent 0 }}
{{- end }}
