# Default values for sysflowagent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# podSecurityContext:
  # fsGroup: 2000

# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: true
#   runAsNonRoot: true
#   runAsUser: 1001

livenessProbe:
  exec:
    command: [ "test", "-e", "/sock/sysflow.sock" ]
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

resources:
  requests:
    cpu: 600m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

sfcollector:
  repository: sysflowtelemetry/sf-collector
  tag: edge
  imagePullPolicy: Always
  filter: '"container.name!=sfprocessor and container.name!=sfcollector"'
  interval: 300

sfprocessor:
  repository: sysflowtelemetry/sf-processor
  tag: edge
  imagePullPolicy: Always
  export: terminal
  syslogHost: localhost
  syslogPort: 514
  syslogProto: tcp

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
          - {key: kubernetes.io/arch, operator: In, values: [amd64]}
